export default {
    "from_airport_id": 1332,
    "to_airport_id": 3207,
    "trip_type": "Return",
    "departure_date": "2021-08-30",
    "passengers": {
        "adults": 1,
        "children": "1",
        "babies": 0
    },
    "class": "Business",
    "return_date": "2021-09-01",
    "flightsDeparture": [
        {
            "id": 1,
            "flight_number": "VN 789",
            "departure_id": 1332,
            "destination_id": 3207,
            "departure_time": "2021-08-30 01:00:00",
            "arrival_time": "2021-08-30 02:00:00",
            "created_at": "2021-08-15T11:29:38.000000Z",
            "updated_at": "2021-08-30T09:27:40.000000Z",
            "business_seats": "[[false,true,true,true],[false,true,false,true],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false]]",
            "economy_seats": "[[true,true,true,true,true,true,false,false,false,false],[true,true,true,false,false,false,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false]]",
            "economy_seat_count": 234,
            "business_seat_count": 5,
            "fare_economy": 1357000,
            "fare_business": 2691000,
            "skymiles": 1161,
            "airport_from": {
                "id": 1332,
                "code": "HAN",
                "name": "Noibai Airport",
                "citycode": "HAN",
                "cityname": "Hanoi",
                "countryname": "VIET NAM",
                "countrycode": "VN",
                "timezone": "7",
                "lat": "21.221192",
                "lon": "105.807178",
                "numairports": 1,
                "city": "true",
                "created_at": null,
                "updated_at": null
            },
            "airport_to": {
                "id": 3207,
                "code": "SGN",
                "name": "Tan Son Nhut Airport",
                "citycode": "SGN",
                "cityname": "Ho Chi Minh City",
                "countryname": "VIET NAM",
                "countrycode": "VN",
                "timezone": "7",
                "lat": "10.818797",
                "lon": "106.651856",
                "numairports": 1,
                "city": "true",
                "created_at": null,
                "updated_at": null
            },
            "origin": {
                "id": 1332,
                "code": "HAN",
                "name": "Noibai Airport",
                "citycode": "HAN",
                "cityname": "Hanoi",
                "countryname": "VIET NAM",
                "countrycode": "VN",
                "timezone": "7",
                "lat": "21.221192",
                "lon": "105.807178",
                "numairports": 1,
                "city": "true",
                "created_at": null,
                "updated_at": null,
                "label": "Hanoi HAN"
            },
            "destination": {
                "id": 3207,
                "code": "SGN",
                "name": "Tan Son Nhut Airport",
                "citycode": "SGN",
                "cityname": "Ho Chi Minh City",
                "countryname": "VIET NAM",
                "countrycode": "VN",
                "timezone": "7",
                "lat": "10.818797",
                "lon": "106.651856",
                "numairports": 1,
                "city": "true",
                "created_at": null,
                "updated_at": null,
                "label": "Ho Chi Minh City SGN"
            }
        }
    ],
    "flightsReturn": [
        {
            "id": 2,
            "flight_number": "VN 987",
            "departure_id": 3207,
            "destination_id": 1332,
            "departure_time": "2021-09-01 21:00:00",
            "arrival_time": "2021-09-01 23:00:00",
            "created_at": "2021-08-15T11:30:11.000000Z",
            "updated_at": "2021-08-30T09:25:05.000000Z",
            "business_seats": "[[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false]]",
            "economy_seats": "[[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,true,true,true],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,true,true,true],[false,false,false,false,false,false,false,true,true,true],[false,false,false,false,false,false,false,true,true,true],[false,false,false,false,false,false,false,true,true,true],[false,false,false,false,false,false,false,true,true,true],[false,false,false,false,false,false,false,true,true,true],[false,false,false,false,false,false,false,true,true,true],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false]]",
            "economy_seat_count": 279,
            "business_seat_count": 40,
            "fare_economy": 1357000,
            "fare_business": 2691000,
            "skymiles": 1161,
            "airport_from": {
                "id": 3207,
                "code": "SGN",
                "name": "Tan Son Nhut Airport",
                "citycode": "SGN",
                "cityname": "Ho Chi Minh City",
                "countryname": "VIET NAM",
                "countrycode": "VN",
                "timezone": "7",
                "lat": "10.818797",
                "lon": "106.651856",
                "numairports": 1,
                "city": "true",
                "created_at": null,
                "updated_at": null
            },
            "airport_to": {
                "id": 1332,
                "code": "HAN",
                "name": "Noibai Airport",
                "citycode": "HAN",
                "cityname": "Hanoi",
                "countryname": "VIET NAM",
                "countrycode": "VN",
                "timezone": "7",
                "lat": "21.221192",
                "lon": "105.807178",
                "numairports": 1,
                "city": "true",
                "created_at": null,
                "updated_at": null
            },
            "origin": {
                "id": 3207,
                "code": "SGN",
                "name": "Tan Son Nhut Airport",
                "citycode": "SGN",
                "cityname": "Ho Chi Minh City",
                "countryname": "VIET NAM",
                "countrycode": "VN",
                "timezone": "7",
                "lat": "10.818797",
                "lon": "106.651856",
                "numairports": 1,
                "city": "true",
                "created_at": null,
                "updated_at": null,
                "label": "Ho Chi Minh City SGN"
            },
            "destination": {
                "id": 1332,
                "code": "HAN",
                "name": "Noibai Airport",
                "citycode": "HAN",
                "cityname": "Hanoi",
                "countryname": "VIET NAM",
                "countrycode": "VN",
                "timezone": "7",
                "lat": "21.221192",
                "lon": "105.807178",
                "numairports": 1,
                "city": "true",
                "created_at": null,
                "updated_at": null,
                "label": "Hanoi HAN"
            }
        }
    ],
    "selectedFlightDeparture": {
        "id": 1,
        "flight_number": "VN 789",
        "departure_id": 1332,
        "destination_id": 3207,
        "departure_time": "2021-08-30 01:00:00",
        "arrival_time": "2021-08-30 02:00:00",
        "created_at": "2021-08-15T11:29:38.000000Z",
        "updated_at": "2021-08-30T09:27:40.000000Z",
        "business_seats": "[[false,true,true,true],[false,true,false,true],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false]]",
        "economy_seats": "[[true,true,true,true,true,true,false,false,false,false],[true,true,true,false,false,false,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false]]",
        "economy_seat_count": 234,
        "business_seat_count": 5,
        "fare_economy": 1357000,
        "fare_business": 2691000,
        "skymiles": 1161,
        "airport_from": {
            "id": 1332,
            "code": "HAN",
            "name": "Noibai Airport",
            "citycode": "HAN",
            "cityname": "Hanoi",
            "countryname": "VIET NAM",
            "countrycode": "VN",
            "timezone": "7",
            "lat": "21.221192",
            "lon": "105.807178",
            "numairports": 1,
            "city": "true",
            "created_at": null,
            "updated_at": null
        },
        "airport_to": {
            "id": 3207,
            "code": "SGN",
            "name": "Tan Son Nhut Airport",
            "citycode": "SGN",
            "cityname": "Ho Chi Minh City",
            "countryname": "VIET NAM",
            "countrycode": "VN",
            "timezone": "7",
            "lat": "10.818797",
            "lon": "106.651856",
            "numairports": 1,
            "city": "true",
            "created_at": null,
            "updated_at": null
        },
        "origin": {
            "id": 1332,
            "code": "HAN",
            "name": "Noibai Airport",
            "citycode": "HAN",
            "cityname": "Hanoi",
            "countryname": "VIET NAM",
            "countrycode": "VN",
            "timezone": "7",
            "lat": "21.221192",
            "lon": "105.807178",
            "numairports": 1,
            "city": "true",
            "created_at": null,
            "updated_at": null,
            "label": "Hanoi HAN"
        },
        "destination": {
            "id": 3207,
            "code": "SGN",
            "name": "Tan Son Nhut Airport",
            "citycode": "SGN",
            "cityname": "Ho Chi Minh City",
            "countryname": "VIET NAM",
            "countrycode": "VN",
            "timezone": "7",
            "lat": "10.818797",
            "lon": "106.651856",
            "numairports": 1,
            "city": "true",
            "created_at": null,
            "updated_at": null,
            "label": "Ho Chi Minh City SGN"
        }
    },
    "selectedFlightReturn": {
        "id": 2,
        "flight_number": "VN 987",
        "departure_id": 3207,
        "destination_id": 1332,
        "departure_time": "2021-09-01 21:00:00",
        "arrival_time": "2021-09-01 23:00:00",
        "created_at": "2021-08-15T11:30:11.000000Z",
        "updated_at": "2021-08-30T09:25:05.000000Z",
        "business_seats": "[[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false]]",
        "economy_seats": "[[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,true,true,true],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,true,true,true],[false,false,false,false,false,false,false,true,true,true],[false,false,false,false,false,false,false,true,true,true],[false,false,false,false,false,false,false,true,true,true],[false,false,false,false,false,false,false,true,true,true],[false,false,false,false,false,false,false,true,true,true],[false,false,false,false,false,false,false,true,true,true],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false]]",
        "economy_seat_count": 279,
        "business_seat_count": 40,
        "fare_economy": 1357000,
        "fare_business": 2691000,
        "skymiles": 1161,
        "airport_from": {
            "id": 3207,
            "code": "SGN",
            "name": "Tan Son Nhut Airport",
            "citycode": "SGN",
            "cityname": "Ho Chi Minh City",
            "countryname": "VIET NAM",
            "countrycode": "VN",
            "timezone": "7",
            "lat": "10.818797",
            "lon": "106.651856",
            "numairports": 1,
            "city": "true",
            "created_at": null,
            "updated_at": null
        },
        "airport_to": {
            "id": 1332,
            "code": "HAN",
            "name": "Noibai Airport",
            "citycode": "HAN",
            "cityname": "Hanoi",
            "countryname": "VIET NAM",
            "countrycode": "VN",
            "timezone": "7",
            "lat": "21.221192",
            "lon": "105.807178",
            "numairports": 1,
            "city": "true",
            "created_at": null,
            "updated_at": null
        },
        "origin": {
            "id": 3207,
            "code": "SGN",
            "name": "Tan Son Nhut Airport",
            "citycode": "SGN",
            "cityname": "Ho Chi Minh City",
            "countryname": "VIET NAM",
            "countrycode": "VN",
            "timezone": "7",
            "lat": "10.818797",
            "lon": "106.651856",
            "numairports": 1,
            "city": "true",
            "created_at": null,
            "updated_at": null,
            "label": "Ho Chi Minh City SGN"
        },
        "destination": {
            "id": 1332,
            "code": "HAN",
            "name": "Noibai Airport",
            "citycode": "HAN",
            "cityname": "Hanoi",
            "countryname": "VIET NAM",
            "countrycode": "VN",
            "timezone": "7",
            "lat": "21.221192",
            "lon": "105.807178",
            "numairports": 1,
            "city": "true",
            "created_at": null,
            "updated_at": null,
            "label": "Hanoi HAN"
        }
    },
    "passengerDetails": [
        {
            "title": "Mr",
            "firstName": "Thinh",
            "lastName": "Nguyen",
            "dateOfBirth": "2021-08-18",
            "nationality": "AD",
            "nationalityId": -1,
            "passportNumber": "C234234",
            "passportExpiryDate": "2021-08-31",
            "travelDocumentType": "Passport",
            "travelDocumentCountry": "AO",
            "seatDeparture": "Business 2 B",
            "seatReturn": "Business 1 A"
        },
        {
            "title": "Mrs",
            "firstName": "Huong",
            "lastName": "Nguyen",
            "dateOfBirth": "2021-08-28",
            "nationality": "AD",
            "nationalityId": -1,
            "passportNumber": "C23423",
            "passportExpiryDate": "2021-08-31",
            "travelDocumentType": "Passport",
            "travelDocumentCountry": "AI",
            "seatDeparture": "Business 1 A",
            "seatReturn": "Business 2 B"
        }
    ],
    "contact": {
        "email": "nvt0412@gmail.com",
        "name": "Thinh Nguyen"
    }
}