export default {
    "from_airport_id": 1934,
    "to_airport_id": 2307,
    "trip_type": "Return",
    "departure_date": "2021-08-19",
    "return_date": "2021-08-21",
    "passenger_count": 2,
    "class": "Business",
    "flightsDeparture": [
        {
            "id": 4,
            "flight_number": "RU66",
            "departure_id": 1934,
            "destination_id": 2307,
            "departure_time": "2021-08-19 11:00:00",
            "arrival_time": "2021-08-19 13:00:00",
            "created_at": "2021-08-07T07:08:26.000000Z",
            "updated_at": "2021-08-07T07:08:26.000000Z",
            "economy_seat_count": 312,
            "business_seat_count": 42,
            "origin": {
                "id": 1934,
                "code": "LED",
                "name": "Pulkovo Airport",
                "citycode": "LED",
                "cityname": "St Petersburg",
                "countryname": "RUSSIA",
                "countrycode": "RU",
                "timezone": "4",
                "lat": "59.800292",
                "lon": "30.262503",
                "numairports": 2,
                "city": "true",
                "created_at": null,
                "updated_at": null,
                "label": "St Petersburg LED"
            },
            "destination": {
                "id": 2307,
                "code": "SVO",
                "name": "Sheremetyevo Airport",
                "citycode": "MOW",
                "cityname": "Moscow",
                "countryname": "RUSSIA",
                "countrycode": "RU",
                "timezone": "4",
                "lat": "55.972642",
                "lon": "37.414589",
                "numairports": 3,
                "city": "",
                "created_at": null,
                "updated_at": null,
                "label": "Moscow SVO"
            }
        },
        {
            "id": 7,
            "flight_number": "RU345",
            "departure_id": 1934,
            "destination_id": 2307,
            "departure_time": "2021-08-19 23:00:00",
            "arrival_time": "2021-08-20 01:00:00",
            "created_at": "2021-08-08T10:24:51.000000Z",
            "updated_at": "2021-08-08T10:24:51.000000Z",
            "economy_seat_count": 312,
            "business_seat_count": 42,
            "origin": {
                "id": 1934,
                "code": "LED",
                "name": "Pulkovo Airport",
                "citycode": "LED",
                "cityname": "St Petersburg",
                "countryname": "RUSSIA",
                "countrycode": "RU",
                "timezone": "4",
                "lat": "59.800292",
                "lon": "30.262503",
                "numairports": 2,
                "city": "true",
                "created_at": null,
                "updated_at": null,
                "label": "St Petersburg LED"
            },
            "destination": {
                "id": 2307,
                "code": "SVO",
                "name": "Sheremetyevo Airport",
                "citycode": "MOW",
                "cityname": "Moscow",
                "countryname": "RUSSIA",
                "countrycode": "RU",
                "timezone": "4",
                "lat": "55.972642",
                "lon": "37.414589",
                "numairports": 3,
                "city": "",
                "created_at": null,
                "updated_at": null,
                "label": "Moscow SVO"
            }
        }
    ],
    "flightsReturn": [
        {
            "id": 8,
            "flight_number": "RU 556",
            "departure_id": 2307,
            "destination_id": 1934,
            "departure_time": "2021-08-21 22:00:00",
            "arrival_time": "2021-08-21 23:00:00",
            "created_at": "2021-08-09T03:13:31.000000Z",
            "updated_at": "2021-08-09T03:13:31.000000Z",
            "economy_seat_count": 312,
            "business_seat_count": 42,
            "origin": {
                "id": 2307,
                "code": "SVO",
                "name": "Sheremetyevo Airport",
                "citycode": "MOW",
                "cityname": "Moscow",
                "countryname": "RUSSIA",
                "countrycode": "RU",
                "timezone": "4",
                "lat": "55.972642",
                "lon": "37.414589",
                "numairports": 3,
                "city": "",
                "created_at": null,
                "updated_at": null,
                "label": "Moscow SVO"
            },
            "destination": {
                "id": 1934,
                "code": "LED",
                "name": "Pulkovo Airport",
                "citycode": "LED",
                "cityname": "St Petersburg",
                "countryname": "RUSSIA",
                "countrycode": "RU",
                "timezone": "4",
                "lat": "59.800292",
                "lon": "30.262503",
                "numairports": 2,
                "city": "true",
                "created_at": null,
                "updated_at": null,
                "label": "St Petersburg LED"
            }
        }
    ],
    "selectedFlightDeparture": {
        "id": 4,
        "flight_number": "RU66",
        "departure_id": 1934,
        "destination_id": 2307,
        "departure_time": "2021-08-19 11:00:00",
        "arrival_time": "2021-08-19 13:00:00",
        "created_at": "2021-08-07T07:08:26.000000Z",
        "updated_at": "2021-08-07T07:08:26.000000Z",
        "economy_seat_count": 312,
        "business_seat_count": 42,
        "origin": {
            "id": 1934,
            "code": "LED",
            "name": "Pulkovo Airport",
            "citycode": "LED",
            "cityname": "St Petersburg",
            "countryname": "RUSSIA",
            "countrycode": "RU",
            "timezone": "4",
            "lat": "59.800292",
            "lon": "30.262503",
            "numairports": 2,
            "city": "true",
            "created_at": null,
            "updated_at": null,
            "label": "St Petersburg LED"
        },
        "destination": {
            "id": 2307,
            "code": "SVO",
            "name": "Sheremetyevo Airport",
            "citycode": "MOW",
            "cityname": "Moscow",
            "countryname": "RUSSIA",
            "countrycode": "RU",
            "timezone": "4",
            "lat": "55.972642",
            "lon": "37.414589",
            "numairports": 3,
            "city": "",
            "created_at": null,
            "updated_at": null,
            "label": "Moscow SVO"
        }
    },
    "selectedFlightReturn": {
        "id": 8,
        "flight_number": "RU 556",
        "departure_id": 2307,
        "destination_id": 1934,
        "departure_time": "2021-08-21 22:00:00",
        "arrival_time": "2021-08-21 23:00:00",
        "created_at": "2021-08-09T03:13:31.000000Z",
        "updated_at": "2021-08-09T03:13:31.000000Z",
        "economy_seat_count": 312,
        "business_seat_count": 42,
        "origin": {
            "id": 2307,
            "code": "SVO",
            "name": "Sheremetyevo Airport",
            "citycode": "MOW",
            "cityname": "Moscow",
            "countryname": "RUSSIA",
            "countrycode": "RU",
            "timezone": "4",
            "lat": "55.972642",
            "lon": "37.414589",
            "numairports": 3,
            "city": "",
            "created_at": null,
            "updated_at": null,
            "label": "Moscow SVO"
        },
        "destination": {
            "id": 1934,
            "code": "LED",
            "name": "Pulkovo Airport",
            "citycode": "LED",
            "cityname": "St Petersburg",
            "countryname": "RUSSIA",
            "countrycode": "RU",
            "timezone": "4",
            "lat": "59.800292",
            "lon": "30.262503",
            "numairports": 2,
            "city": "true",
            "created_at": null,
            "updated_at": null,
            "label": "St Petersburg LED"
        }
    },
    "passengers": [
        {
            "title": "Mr",
            "firstName": "Thinh",
            "lastName": "Nguyen",
            "dateOfBirth": "1999-12-08",
            "nationality": "VN",
            "nationalityId": -1,
            "passportNumber": "C12345678",
            "passportExpiryDate": "2022-08-20",
            "travelDocumentType": "Passport",
            "travelDocumentCountry": "VN"
        },
        {
            "title": "Mrs",
            "firstName": "Thi",
            "lastName": "Nguyen",
            "dateOfBirth": "1991-08-10",
            "nationality": "VN",
            "nationalityId": -1,
            "passportNumber": "C87654321",
            "passportExpiryDate": "2023-08-24",
            "travelDocumentType": "Passport",
            "travelDocumentCountry": "VN"
        }
    ],
    "contact": {
        "email": "nvt0412@gmail.com"
    }
}