export default {
    "from_airport_id": 1332,
    "to_airport_id": 3207,
    "trip_type": "Return",
    "departure_date": "2021-08-30",
    "passengers": {
        "adults": "2",
        "children": "1",
        "babies": 0
    },
    "class": "Economy",
    "return_date": "2021-09-01",
    "flightsDeparture": [
        {
            "id": 1,
            "flight_number": "VN 789",
            "departure_id": 1332,
            "destination_id": 3207,
            "departure_time": "2021-08-30 01:00:00",
            "arrival_time": "2021-08-30 02:00:00",
            "created_at": "2021-08-15T11:29:38.000000Z",
            "updated_at": "2021-08-15T11:29:38.000000Z",
            "business_seats": "[[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false]]",
            "economy_seats": "[[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false]]",
            "economy_seat_count": 300,
            "business_seat_count": 10,
            "fare_economy": 58.00995248987101,
            "fare_business": 116.01990497974202,
            "airport_from": {
                "id": 1332,
                "code": "HAN",
                "name": "Noibai Airport",
                "citycode": "HAN",
                "cityname": "Hanoi",
                "countryname": "VIET NAM",
                "countrycode": "VN",
                "timezone": "7",
                "lat": "21.221192",
                "lon": "105.807178",
                "numairports": 1,
                "city": "true",
                "created_at": null,
                "updated_at": null
            },
            "airport_to": {
                "id": 3207,
                "code": "SGN",
                "name": "Tan Son Nhut Airport",
                "citycode": "SGN",
                "cityname": "Ho Chi Minh City",
                "countryname": "VIET NAM",
                "countrycode": "VN",
                "timezone": "7",
                "lat": "10.818797",
                "lon": "106.651856",
                "numairports": 1,
                "city": "true",
                "created_at": null,
                "updated_at": null
            },
            "origin": {
                "id": 1332,
                "code": "HAN",
                "name": "Noibai Airport",
                "citycode": "HAN",
                "cityname": "Hanoi",
                "countryname": "VIET NAM",
                "countrycode": "VN",
                "timezone": "7",
                "lat": "21.221192",
                "lon": "105.807178",
                "numairports": 1,
                "city": "true",
                "created_at": null,
                "updated_at": null,
                "label": "Hanoi HAN"
            },
            "destination": {
                "id": 3207,
                "code": "SGN",
                "name": "Tan Son Nhut Airport",
                "citycode": "SGN",
                "cityname": "Ho Chi Minh City",
                "countryname": "VIET NAM",
                "countrycode": "VN",
                "timezone": "7",
                "lat": "10.818797",
                "lon": "106.651856",
                "numairports": 1,
                "city": "true",
                "created_at": null,
                "updated_at": null,
                "label": "Ho Chi Minh City SGN"
            }
        }
    ],
    "flightsReturn": [
        {
            "id": 2,
            "flight_number": "VN 987",
            "departure_id": 3207,
            "destination_id": 1332,
            "departure_time": "2021-09-01 21:00:00",
            "arrival_time": "2021-09-01 23:00:00",
            "created_at": "2021-08-15T11:30:11.000000Z",
            "updated_at": "2021-08-15T11:30:11.000000Z",
            "business_seats": "[[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false]]",
            "economy_seats": "[[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false]]",
            "economy_seat_count": 300,
            "business_seat_count": 40,
            "fare_economy": 58.00995248987101,
            "fare_business": 116.01990497974202,
            "airport_from": {
                "id": 3207,
                "code": "SGN",
                "name": "Tan Son Nhut Airport",
                "citycode": "SGN",
                "cityname": "Ho Chi Minh City",
                "countryname": "VIET NAM",
                "countrycode": "VN",
                "timezone": "7",
                "lat": "10.818797",
                "lon": "106.651856",
                "numairports": 1,
                "city": "true",
                "created_at": null,
                "updated_at": null
            },
            "airport_to": {
                "id": 1332,
                "code": "HAN",
                "name": "Noibai Airport",
                "citycode": "HAN",
                "cityname": "Hanoi",
                "countryname": "VIET NAM",
                "countrycode": "VN",
                "timezone": "7",
                "lat": "21.221192",
                "lon": "105.807178",
                "numairports": 1,
                "city": "true",
                "created_at": null,
                "updated_at": null
            },
            "origin": {
                "id": 3207,
                "code": "SGN",
                "name": "Tan Son Nhut Airport",
                "citycode": "SGN",
                "cityname": "Ho Chi Minh City",
                "countryname": "VIET NAM",
                "countrycode": "VN",
                "timezone": "7",
                "lat": "10.818797",
                "lon": "106.651856",
                "numairports": 1,
                "city": "true",
                "created_at": null,
                "updated_at": null,
                "label": "Ho Chi Minh City SGN"
            },
            "destination": {
                "id": 1332,
                "code": "HAN",
                "name": "Noibai Airport",
                "citycode": "HAN",
                "cityname": "Hanoi",
                "countryname": "VIET NAM",
                "countrycode": "VN",
                "timezone": "7",
                "lat": "21.221192",
                "lon": "105.807178",
                "numairports": 1,
                "city": "true",
                "created_at": null,
                "updated_at": null,
                "label": "Hanoi HAN"
            }
        }
    ],
    "selectedFlightDeparture": {
        "id": 1,
        "flight_number": "VN 789",
        "departure_id": 1332,
        "destination_id": 3207,
        "departure_time": "2021-08-30 01:00:00",
        "arrival_time": "2021-08-30 02:00:00",
        "created_at": "2021-08-15T11:29:38.000000Z",
        "updated_at": "2021-08-15T11:29:38.000000Z",
        "business_seats": "[[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false]]",
        "economy_seats": "[[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false]]",
        "economy_seat_count": 300,
        "business_seat_count": 10,
        "fare_economy": 58.00995248987101,
        "fare_business": 116.01990497974202,
        "airport_from": {
            "id": 1332,
            "code": "HAN",
            "name": "Noibai Airport",
            "citycode": "HAN",
            "cityname": "Hanoi",
            "countryname": "VIET NAM",
            "countrycode": "VN",
            "timezone": "7",
            "lat": "21.221192",
            "lon": "105.807178",
            "numairports": 1,
            "city": "true",
            "created_at": null,
            "updated_at": null
        },
        "airport_to": {
            "id": 3207,
            "code": "SGN",
            "name": "Tan Son Nhut Airport",
            "citycode": "SGN",
            "cityname": "Ho Chi Minh City",
            "countryname": "VIET NAM",
            "countrycode": "VN",
            "timezone": "7",
            "lat": "10.818797",
            "lon": "106.651856",
            "numairports": 1,
            "city": "true",
            "created_at": null,
            "updated_at": null
        },
        "origin": {
            "id": 1332,
            "code": "HAN",
            "name": "Noibai Airport",
            "citycode": "HAN",
            "cityname": "Hanoi",
            "countryname": "VIET NAM",
            "countrycode": "VN",
            "timezone": "7",
            "lat": "21.221192",
            "lon": "105.807178",
            "numairports": 1,
            "city": "true",
            "created_at": null,
            "updated_at": null,
            "label": "Hanoi HAN"
        },
        "destination": {
            "id": 3207,
            "code": "SGN",
            "name": "Tan Son Nhut Airport",
            "citycode": "SGN",
            "cityname": "Ho Chi Minh City",
            "countryname": "VIET NAM",
            "countrycode": "VN",
            "timezone": "7",
            "lat": "10.818797",
            "lon": "106.651856",
            "numairports": 1,
            "city": "true",
            "created_at": null,
            "updated_at": null,
            "label": "Ho Chi Minh City SGN"
        }
    },
    "selectedFlightReturn": {
        "id": 2,
        "flight_number": "VN 987",
        "departure_id": 3207,
        "destination_id": 1332,
        "departure_time": "2021-09-01 21:00:00",
        "arrival_time": "2021-09-01 23:00:00",
        "created_at": "2021-08-15T11:30:11.000000Z",
        "updated_at": "2021-08-15T11:30:11.000000Z",
        "business_seats": "[[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false]]",
        "economy_seats": "[[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false]]",
        "economy_seat_count": 300,
        "business_seat_count": 40,
        "fare_economy": 58.00995248987101,
        "fare_business": 116.01990497974202,
        "airport_from": {
            "id": 3207,
            "code": "SGN",
            "name": "Tan Son Nhut Airport",
            "citycode": "SGN",
            "cityname": "Ho Chi Minh City",
            "countryname": "VIET NAM",
            "countrycode": "VN",
            "timezone": "7",
            "lat": "10.818797",
            "lon": "106.651856",
            "numairports": 1,
            "city": "true",
            "created_at": null,
            "updated_at": null
        },
        "airport_to": {
            "id": 1332,
            "code": "HAN",
            "name": "Noibai Airport",
            "citycode": "HAN",
            "cityname": "Hanoi",
            "countryname": "VIET NAM",
            "countrycode": "VN",
            "timezone": "7",
            "lat": "21.221192",
            "lon": "105.807178",
            "numairports": 1,
            "city": "true",
            "created_at": null,
            "updated_at": null
        },
        "origin": {
            "id": 3207,
            "code": "SGN",
            "name": "Tan Son Nhut Airport",
            "citycode": "SGN",
            "cityname": "Ho Chi Minh City",
            "countryname": "VIET NAM",
            "countrycode": "VN",
            "timezone": "7",
            "lat": "10.818797",
            "lon": "106.651856",
            "numairports": 1,
            "city": "true",
            "created_at": null,
            "updated_at": null,
            "label": "Ho Chi Minh City SGN"
        },
        "destination": {
            "id": 1332,
            "code": "HAN",
            "name": "Noibai Airport",
            "citycode": "HAN",
            "cityname": "Hanoi",
            "countryname": "VIET NAM",
            "countrycode": "VN",
            "timezone": "7",
            "lat": "21.221192",
            "lon": "105.807178",
            "numairports": 1,
            "city": "true",
            "created_at": null,
            "updated_at": null,
            "label": "Hanoi HAN"
        }
    },
    "passengerDetails": [
        {
            "title": "Mr",
            "firstName": "A",
            "lastName": "Nguyen",
            "dateOfBirth": "1999-12-04",
            "nationality": "VN",
            "nationalityId": -1,
            "passportNumber": "C12345678",
            "passportExpiryDate": "2022-08-26",
            "travelDocumentType": "Passport",
            "travelDocumentCountry": "VN",
            "seatDeparture": "Economy 21 D",
            "seatReturn": "Economy 21 H"
        },
        {
            "title": "Mrs",
            "firstName": "E",
            "lastName": "Nguyen",
            "dateOfBirth": "1999-01-03",
            "nationality": "VN",
            "nationalityId": -1,
            "passportNumber": "C23456781",
            "passportExpiryDate": "2022-08-31",
            "travelDocumentType": "Passport",
            "travelDocumentCountry": "VN",
            "seatDeparture": "Economy 21 E",
            "seatReturn": "Economy 21 J"
        },
        {
            "title": "Ms",
            "firstName": "I",
            "lastName": "Nguyen",
            "dateOfBirth": "2018-08-08",
            "nationality": "VN",
            "nationalityId": -1,
            "passportNumber": "C3456712",
            "passportExpiryDate": "2022-08-31",
            "travelDocumentType": "Passport",
            "travelDocumentCountry": "VN",
            "seatDeparture": "Economy 21 F",
            "seatReturn": "Economy 21 K"
        }
    ],
    "contact": {
        "email": "nvt0412@gmail.com"
    }
}